medical_specialties = {
    "Tüp Bebek": "IN VITRO FERTILIZATION",
    "Genel Cerrahi": "General Surgery",
    "Fizik Tedavi ve Rehabilitasyon": "Physical Treatment and Rehabilitation",
    "Çocuk Sağlığı ve Hastalıkları": "Pediatrics",
    "Gastroenteroloji": "Gastroenterology",
    "Diş ve Protez": "X Orthesis and Prosthesis",
    "Patoloji": "Pathology",
    "İç Hastalıkları (Dahiliye)": "Internal Medicine",
    "İç Hastalıkları" : "Internal Medicine",
    "Göz Hastalıkları ve Sağlığı": "Ophthalmology",
    "Kardiyoloji": "Cardiology",
    "Kadın Hastalıkları ve Doğum": "Gynecology and Obstetrics",
    "Ortopedi ve Travmatoloji": "Orthopedics and Traumatology",
    "Üroloji": "Urology",
    "Estetik, Plastik ve Rekonstrüktif Cerrahi": "Aesthetics and Plastic Reconstructive Surgery",
    "Plastik ve Rekontrüktif Cerrrahi": "Aesthetics and Plastic Reconstructive Surgery",
    "Radyoloji": "Radiology",
    "Anestezi ve Reanimasyon": "Anesthesia and Reanimation",
    "Kulak, Burun, Boğaz ve  Baş Boyun Cerrahisi": "Otorhinolaryngology",
    "Kulak Burun Boğaz Hastalıkları" : "Otorhinolaryngology",
    "Nöroloji": "Neurology",
    "Kalp ve Damar Cerrahisi": "Cardiovascular Surgery",
    "Göz Sağlığı ve Hastalıkları": "Eye Health and Diseases",
    "Dermatoloji (Cilt Hastalıkları)": "Skin Diseases",
    "Cilt Hastalıkları": "Skin Diseases",
    "Göğüs Hastalıkları": "Pulmonology",
    "Psikiyatri": "Psychiatry",
    "Ağız, Diş ve Çene Cerrahisi - İmplantoloji": "Oral, Dental and Maxillofacial Surgery",
    "Ortodonti": "Orthodontics",
    "Periodontoloji (Diş Eti Hastalıkları)": "Periodontology (Gingival Diseases)",
    "Diş Hekimi": "Dentist",
    "Pedodonti (Çocuk Diş Hekimi)": "Pedodontics (Pediatric Dentistry)",
    "Laboratuvar": "Laboratory",
    "Odyoloji ve Konuşma Bozuklukları": "Language and Speech Disorders",
    "Beslenme ve Diyet": "Nutrition and Diet",
    "Podoloji": "Techniques Podology",
    "Psikoloji": "Psychology",
}



def decodeTurkishText(text):
    return text